# https://github.com/vn7n24fzkq/github-profile-summary-cards

name: Update Profile Summary Cards

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * 5"

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v2
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          USERNAME: ${{ github.repository_owner }}
